const V2_OUTPUT0_LABEL = 0x22;
const V2_INPUT0_LABEL = 0x27;
const V2_OUTPUT1_LABEL = 0x2c;
const V2_INPUT1_LABEL = 0x31;
const SEPPUKU_LABEL = 0x36;
const RECOVER_ETH_LABEL = 0x3b;
const RECOVER_WETH_LABEL = 0x40;
const DEPOSIT_WETH_LABEL = 0x45;
module.exports = {
  V2_OUTPUT0_LABEL,
  V2_INPUT0_LABEL,
  V2_OUTPUT1_LABEL,
  V2_INPUT1_LABEL,
  SEPPUKU_LABEL,
  RECOVER_ETH_LABEL,
  RECOVER_WETH_LABEL,
  DEPOSIT_WETH_LABEL,
};
